### ISSUE TITLE
Dragging email address causes field reset in Typebot.

### ISSUE THREAD

**Issue by hyunbinseo** [baptisteArno/baptistearno-dot-com#1]
When subscribing to the news letter, dragging and then releasing the entered email address causes a field reset.

https://user-images.githubusercontent.com/47051820/173280014-a64114cc-e061-4581-9221-8b72644183ac.mp4

Can be reproduced in the following environments
- Microsoft Windows 21H2 `19044.1706`
  - Google Chrome `102.0.5005.115`
  - Firefox `102.0b7`

I am not sure if this a Typebot issue, so I am creating an issue in this repository.

**Comment by baptisteArno** [comment]
Hey my friend, thank you for the info 😀

I'm curious, what is your intention when you try to select your email?

**Comment by hyunbinseo** [comment]
I didn't want to type my first name, so I tried to copy my email address.

**Comment by baptisteArno** [comment]
Thank you for opening an issue :)

It will be fixed in next release 👍
